# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# Add current directory to path
current_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['msts_consist_editor_gui.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('consistEditor.py', '.'),
        ('msts_consist_cli.py', '.'),
        ('requirements.txt', '.'),
        ('engines_store.txt', '.'),
        ('wagons_store.txt', '.'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'tkinter.simpledialog',
        'pathlib',
        'threading',
        'subprocess',
        'sys',
        'os',
        'shutil',
        'queue',
        'time',
        'json',
        're',
        'collections',
        'difflib',
        'enum',
        'typing',
        'functools',
        'itertools',
        'multiprocessing',
        'concurrent.futures',
        'fuzzywuzzy',
        'fuzzywuzzy.fuzz',
        'fuzzywuzzy.process',
        'colorama',
        'colorama.Fore',
        'colorama.Back',
        'colorama.Style',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'sklearn',
        'tensorflow',
        'torch',
        'PIL',
        'cv2',
        'flask',
        'django',
        'fastapi',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MSTS_Consist_Editor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version=None,
)
